name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node and dependencies
        uses: mongodb-labs/drivers-github-tools/node/setup@v2

      - run: npm run check:lint
