name: unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm clean-install
      - run: npm run check:test

  test-latest-driver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm clean-install
      - run: npm install --no-save mongodb/node-mongodb-native#main
      - run: npm run check:test

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm clean-install
    - run: npm run check:coverage
    - name: code coverage results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage
        retention-days: 1
